SELECT DEPARTMENT_NAME AS 'DEPARTMENT NAME', 
COUNT(*) AS 'NO. OF EMPLOYEES' 
FROM DEPARTMENTS
INNER JOIN EMPLOYEES 
ON EMPLOYEES .DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
GROUP BY DEPARTMENTS.DEPARTMENT_ID, DEPARTMENT_NAME
ORDER BY DEPARTMENT_NAME;