SELECT FIRSTNAME, LASTNAME FROM EMPLOYEES WHERE MANAGER_ID 
IN (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE DEPARTMENT_ID
IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE LOCATION_ID 
IN (SELECT LOCATION_ID FROM LOCATIONS WHERE  COUNTRY_ID='US')));