SELECT e.FIRSTNAME, e.LASTNAME, e.JOB_ID, e.DEPARTMENT_ID, d.DEPARTMENT_NAME
FROM EMPLOYEES e JOIN DEPARTMENTS d 
ON (e.DEPARTMENT_ID = d.DEPARTMENT_ID) JOIN LOCATIONS l ON (d.LOCATION_ID = l.LOCATION_ID) 
WHERE LOWER(l.CITY) = 'London';