SELECT FIRSTNAME, LASTNAME, SALARY FROM EMPLOYEES 
WHERE DEPARTMENT_ID IN 
(SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME LIKE 'IT%') 
AND SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);