SELECT 	E.LASTNAME, E.JOB_ID, E.DEPARTMENT_ID,D.DEPARTMENT_NAME
FROM 	EMPLOYEES E JOIN DEPARTMENTS D
ON 	(E.DEPARTMENT_ID = D.DEPARTMENT_ID)
JOIN 	LOCATIONS L
ON 	(D.LOCATION_ID = L.LOCATION_ID)
WHERE 	LOWER(L.city) = 'Toronto';